### ISSUE TITLE
Plugin v1.9.0 using the wrong credentials

### ISSUE THREAD

**Issue by Ewanuk** [SRombauts/UEPlasticPlugin#142]
Problem: I work for two organizations and I need different credentials for each one.

On my second project when I open settings:
![image](https://github.com/SRombauts/UEPlasticPlugin/assets/8235469/33a0c6b5-8718-43df-84b9-a44735ce0bc9)

The username is still on the credentials I need for my first project. As a result, I can't check anything in. How do I log into a different account on a per-project basis?

**Comment by SRombautsU** [comment]
Hello,
would you be able to check with a more recent version of the plugin? I see you are using 1.9.0 coming from UE5.4.

I think that your issue has been reported some time already, it looks like similar to what I tried to fix with 
https://github.com/PlasticSCM/UEPlasticPlugin/pull/105 
This fix has been released in 1.10.0 that you can get from the Marketplace https://www.unrealengine.com/marketplace/en-US/product/unity-version-control-plastic-scm (or from Github)

In am not entirely sure because I don't have your logs to see exactly what is going on in your case.

If updating doesn't fix the issue, please submit a ticket for [technical support](https://support.unity.com/hc/en-us/requests/new?ticket_form_id=360001051792?utm_source=unreal) but please provide all the important info (versions etc) and especially the log from Unreal and the log from "cm" are needed (see https://docs.plasticscm.com/technical-articles/kb-enabling-logging-for-plastic-scm-part-i)

Let me know how it goes,
Sébastien

**Comment by SRombauts** [comment]
I am closing this as I could confirm it working with 1.10.1

**Comment by Ewanuk** [comment]
I've updated to v1.11.0 and I'm seeing a similar issue.

My username is correct, but I'm still getting invalid credential errors. I've checked my client.conf for Unity Source Control and that is still storing the credentials to the other project I'm working with.

I can use the Unity Source Control client just fine with both credentials, so wherever they're stored locally on my machine is probably correct. Is possible the plugin is still using the wrong credentials or does it store it separately?

**Comment by SRombauts** [comment]
Hello, I am sorry to hear that, I think that you are hitting a bug that isn't si easy to reproduce

The plugin, and Unreal, aren't storing any credentials and the plugin doesn't handle anything except displaying names in some place

So it means that the issue is somewhere in the Command Line Interface (cm.exe) or in it's configuration (client.conf and profiles.conf)

Ideally you could try to test using the command line on the same workspace and see that it should indeed have the same issue; then you could try to use the configure command to set the proposer credentials 

Would you be able to provide me as many logs and files as possible? If you prefer send them to Unity support team as they would treat them with the proper confidentially (and it's not related to the Unreal Plugin itself)

Don't hesitate to ask for help, I can provide more details based on your tests

**Comment by Ewanuk** [comment]
Copying credentials from profiles.conf into client.conf did the trick. It's hacky but oh well.

Where are the logs stored?

**Comment by SRombauts** [comment]
Hello,

Have a look at [Enable Debug logs in the README](https://github.com/SRombauts/UEPlasticPlugin?tab=readme-ov-file#enable-debug-logs)
1. You can enable Verbose logs from Unreal, I'd like to know how the Unreal plugins detect and treat the error so perhaps we can handle the error properly and ask for credentials
2. You can enable debug log for "cm.exe" command line: this will tell us more if the bug is in the low level layers of Unity Version Control

What do you mean exactly by "copying credentials from profiles.conf into client.conf"?

Thanks a lot!

**Comment by SRombautsU** [comment]
I think/I guess that what you did was changing the "default profile" in the client.conf, to point directly to the correct profile instead of the other one that was not working in Unreal:

  <WorkingMode>SSOWorkingMode</WorkingMode>
  <SecurityConfig>sebastien.rombauts@unity3d.com</SecurityConfig>

**Comment by SRombauts** [comment]
Hello,

the fix for this issue was finally released as part of 1.12 [on Github](https://github.com/SRombauts/UEPlasticPlugin/releases/tag/1.12.0) or [on Fab.com](https://www.fab.com/listings/42f9c431-d7a7-4e09-af55-fb4b896e9c97)

Fix 'cm checkconnection' having authentication issues with multiple accounts by @SRombautsU in https://github.com/PlasticSCM/UEPlasticPlugin/pull/128
Works best with [Unity Version Control 11.0.16.9055](https://www.plasticscm.com/download/releasenotes/11.0.16.9055)

Cheers!
